=== EugenePomozov/Java-Training-Lab---Home-Task---Reflection/HomeTask4-XML/src/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<air:schema xmlns:air="http://www.w3.org/2001/XMLSchema">
 
 
 
    <air:element name="flight-schedule">
          <air:complexType>
            <air:sequence>
                <air:element name="schedule" type="Schedule" maxOccurs="unbounded"/>
            </air:sequence>
        </air:complexType>
    </air:element>
    
    
    <air:complexType name="Schedule">
        <air:sequence>
            <air:element name="airline" type="air:string"/>
            <air:element name="aircraft" type="Aircraft"/>
            <air:element name="date-origin" type="air:date"/>
            <air:element name="date-destination" type="air:date"/>
            <air:element name="class" type="Class"/>
            <air:element name="cost" type="air:double"/>
        </air:sequence>
    </air:complexType>
    
    
    <air:simpleType name="Class">
        <air:restriction base="air:string">
            <air:enumeration value="econom"/>
            <air:enumeration value="business"/>
        </air:restriction>
    </air:simpleType>
    
    
    <air:complexType name="Aircraft">
        <air:attribute name="number" type="air:string" use="required"/>
        <air:attribute name="type" type="air:string" use="required"/>
        <air:attribute name="capacity" type="air:integer" use="required"/>
    </air:complexType>
    
    
</air:schema>

=== EugenePomozov/Java-Training-Lab---Home-Task---Reflection/HomeTask4-XML/src/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<flight-schedule xmlns:air="http://www.w3.org/2001/XMLSchema-instance"
                 air:noNamespaceSchemaLocation="schedule.xsd">
    <schedule>
        <airline>Belavia</airline>
        <aircraft number="B2-739" type="Boeing 737" capacity="853"/>
        <date-origin>2016-05-01</date-origin>
        <date-destination>2016-05-01</date-destination>
        <class>business</class>
        <cost>600</cost>
    </schedule>
    
    <schedule>
        <airline>Belavia</airline>
        <aircraft number="ML-439" type="Embraer E190" capacity="114"/>
        <date-origin>2016-05-02</date-origin>
        <date-destination>2016-05-02</date-destination>
        <class>business</class>
        <cost>500</cost>
    </schedule>
    
    <schedule>
        <airline>Air China</airline>
        <aircraft number="KS-8235" type="Embraer 175" capacity="192"/>
        <date-origin>2016-05-03</date-origin>
        <date-destination>2016-05-03</date-destination>
        <class>business</class>
        <cost>400</cost>
    </schedule>
    
    <schedule>
        <airline>Air China</airline>
        <aircraft number="FT-2658" type="Boeing 747" capacity="539"/>
        <date-origin>2016-05-04</date-origin>
        <date-destination>2016-05-04</date-destination>
        <class>econom</class>
        <cost>321</cost>
    </schedule>
    
    <schedule>
        <airline>Air China</airline>
        <aircraft number="KS-8235" type="Embraer 175" capacity="192"/>
        <date-origin>2016-05-03</date-origin>
        <date-destination>2016-05-03</date-destination>
        <class>business</class>
        <cost>400</cost>
    </schedule>
    
</flight-schedule>
